# Generated by Django 3.1.3 on 2020-11-22 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_auto_20201122_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='profile_pic',
        ),
    ]
