# Generated by Django 3.1.3 on 2020-11-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_auto_20201122_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='post',
            name='Image',
            field=models.ImageField(null=True, upload_to='new_post/'),
        ),
    ]
