# Generated by Django 3.1.3 on 2020-11-22 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0005_auto_20201122_2207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Image',
            new_name='profile_pic',
        ),
    ]
